### PR TITLE
fix: Lazily initialise IPC in renderer

### LINKED ISSUE #427: Importing @sentry/electron without calling init() yields an error
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases

## Versions + Platform

- [x] SDK version - `@sentry/electron@3.0.3`
- [x] Electron version - `electron@17.1.0`
- [x] Platform - `Linux`

## Description

We call `init()` conditionally, so that our users have an option to turn off error reporting. This worked fine in `@sentry/electron@2.5.4`, but in `@sentry/electron@3.0.3`, when `init()` is not called, we get this console error in the renderer process from #377:

```
Fetch API cannot load sentry-ipc://sentry-electron.ping. URL scheme "sentry-ipc" is not supported.", source: …/node_modules/@sentry/electron/renderer/ipc.js (15)
Sentry SDK failed to establish connection with the Electron main process.
 - Ensure you have initialized the SDK in the main process
 - If your renderers use custom sessions, be sure to set 'getSessions' in the main process options
 - If you are bundling your main process code and using Electron < v5, you'll need to manually configure a preload script", source: …/node_modules/@sentry/electron/renderer/ipc.js (15)
```

`@sentry/electron` do nothing before `init()` is called (like the documentation [says](https://github.com/getsentry/sentry-electron/#usage)).

### Minimal reproducible example

**`index.js`**

```js
const Sentry = require("@sentry/electron");
const { app, BrowserWindow } = require("electron");

if (false /* we decided not to */) {
  Sentry.init({ dsn: "__DSN__" });
}

app.whenReady().then(() => {
  const win = new BrowserWindow({
    webPreferences: {
      preload: require.resolve("./preload.js"),
    },
  });
  win.loadURL("about:blank");
});
```

**`preload.js`**

```js
const Sentry = require("@sentry/electron");

if (false /* we decided not to */) {
  Sentry.init({ dsn: "__DSN__" });
}
```

**`package.json`**

```json
{
  "dependencies": {
    "@sentry/electron": "^3.0.3",
    "electron": "^17.1.0"
  }
}

### PR DESCRIPTION
**Pull request by timfish**
Fixes #427

### CODE REVIEW

File: src/renderer/ipc.ts [hunk 1]
```diff
@@ -38,10 +36,18 @@ function getImplementation(): IPCInterface {
...
 /**
  * Renderer IPC interface
  *
  * Favours IPC if its been exposed via a preload script but will
  * fallback to custom protocol and fetch is IPC is not available
  */
-export const IPC: IPCInterface = getImplementation();
+export function getIPC(): IPCInterface {
+  if (!cachedInterface) {
+    cachedInterface = getImplementation();
```
Comment (AbhiPrasad) [inline src/renderer/ipc.ts:49]: Will there be any worries about the cache getting stale? Like some condition where `window.__SENTRY_IPC__` somehow changes?

Comment (timfish) [reply src/renderer/ipc.ts:49]: We were only ever calling `getImplementation()` once before. This change just does it lazily rather than at parse time.

**Review by AbhiPrasad — APPROVED** [review]
