### PR TITLE
fix: Many improvements

### LINKED ISSUE #21: URL normalization does cater for URL encoded characters
Like:

```
/C:/Program%20Files/My%20Company/My%20App/resources/app.asar/dist/bundle-app.js
```

### PR DESCRIPTION
**Pull request by timfish**
Changes
- Split tests into `unit` and `e2e`
- Run unit tests in `electron-mocha` and e2e in `mocha`
- Use `ts-node/register` so TypeScript tests don't require pre-compilation step
- Simplify `normalizeUrl` and add some initial tests (Fixes #21)

### CODE REVIEW

File: example/main.js [hunk 1]
```diff
@@ -1,12 +1,17 @@
+const { app, BrowserWindow, ipcMain } = require('electron');
+const path = require('path');
+const url = require('url');
+
+// If we're running e2e tests, use the supplied temp userData directory
+if (process.env['E2E_USERDATA_DIRECTORY']) {
+  app.setPath('userData', process.env['E2E_USERDATA_DIRECTORY']);
+}
+
```
Comment (timfish) [inline example/main.js]: If the app is running e2e tests, we have to change `userData` directory very early, certainly before Sentry is started

File: test/e2e/index.test.ts [hunk 2]
```diff
@@ -1,39 +1,33 @@
...
-    return app.start().then(() => app.client.waitUntilWindowLoaded());
+  beforeEach(async () => {
+    await app.start();
+    await app.client.waitUntilWindowLoaded();
   });
 
-  after(() => {
+  afterEach(async () => {
     if (app && app.isRunning()) {
       return app.stop();
```
Comment (timfish) [inline test/e2e/index.test.ts]: Ideally, every test should run in its own fresh instance of the app

File: test/unit/url-normalize.test.ts [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+    expect(normalizeUrl('/C:/Program%20Files/My%20App/resources/app.asar/dist/bundle-app.js', base))
+      .to.equal('app://dist/bundle-app.js');
+
+    expect(normalizeUrl('file:///C:/Program%20Files/My%20App/resources/app.asar/index.html', base))
+      .to.equal('app://index.html');
+
+    expect(normalizeUrl('file:///C:/Program%20Files/My%20App/resources/app.asar/a/index.html', base))
+      .to.equal('app://a/index.html');
+  });
```
Comment (timfish) [inline test/unit/url-normalize.test.ts]: Still need to check this all on macOS
