### PR TITLE
fix: Guard against invalid queue entries

### LINKED ISSUE #1051: Error possibly caused by the SDK
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

5.8.0

### Electron Version

22.3.27

### What platform are you using?

Windows

### Link to Sentry event

https://desquared.sentry.io/issues/6204868921/?project=4507606472261632

### Steps to Reproduce

The Sentry event I linked does not appear to originate from the customer application's code but rather from our SDK. It points to this file: https://github.com/getsentry/sentry-electron/blob/master/src/main/transports/offline-store.ts

The issue results in a high volume of events being sent.

Zendesk ticket for additional information: https://sentry.zendesk.com/agent/tickets/142036

### Expected Result

The SDK should handle connection timeouts gracefully and not generate excessive error events.

### Actual Result

The SDK generates a large number of error events, causing the customer to reach their error limit.

### PR DESCRIPTION
**Pull request by timfish**
- Closes #1051

I don't know exactly what caused this issue. I suspect it could be due to an invalid read of the data store.

### CODE REVIEW

File: src/main/transports/offline-store.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ export function createOfflineStore(userOptions: Partial<OfflineStoreOptions>): O
     });
   }
 
-  function removeStaleRequests(queue: PersistedRequest[]): void {
+  function removeStaleRequests(queue: Array<Partial<PersistedRequest> | undefined>): void {
     while (queue[0] && isOutdated(queue[0], options.maxAgeDays)) {
```
Comment (AbhiPrasad) [inline src/main/transports/offline-store.ts:67]: given we do the `queue[0]` check here, can we enforce that `isOutdated` gets `Partial<PersistedRequest>` instead of `Partial<PersistedRequest> | undefined`?

**Review by AbhiPrasad — APPROVED** [review]
Let's ship this as a quick fix for now, but I think we should change the store to see if we can detect scenarios where the data is invalid.
