### PR TITLE
fix: Deprecate renderer init options which should only be used in main process

### LINKED ISSUE #1030: Using Sentry Electron with Sentry React will cause the environment tag to be missing
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Electron SDK Version

5.7.0

### Electron Version

28.3.3

### What platform are you using?

MacOS

### Link to Sentry event

_No response_

### Steps to Reproduce

1. Add sentry electron & sentry react to renderer process as the document recommended
https://docs.sentry.io/platforms/javascript/guides/electron/#framework-specific-sdks

```js
import * as Sentry from '@sentry/electron/renderer'
import { init as ReactInit } from '@sentry/react'

Sentry.init(
  {
    dsn: import.meta.env.VITE_SENTRY_DSN,
    environment: process.env.NODE_ENV
  },
  ReactInit
)
```

2. Throw an error in the renderer process function

3. Build the electron app 

4. Occur the function that makes error

5.  Check Sentry error with json format, and there's **no environment attribute** under "tags". 

```json
"tags": [
    [
      "browser.name",
      "Chrome"
    ],
    [
      "chrome",
      "Chrome 120.0.6099.291"
    ],
    [
      "chrome.name",
      "Chrome"
    ],
    [
      "device.family",
      "Desktop"
    ],
    [
      "event.environment",
      "javascript"
    ],
    [
      "event.origin",
      "electron"
    ],
    [
      "event.process",
      "renderer"
    ],
    [
      "handled",
      "yes"
    ],
    [
      "level",
      "error"
    ],
    [
      "mechanism",
      "generic"
    ],
    [
      "node",
      "Node 18.18.2"
    ],
    [
      "node.name",
      "Node"
    ],
    [
      "os",
      "macOS 13.3.1"
    ],
    [
      "os.name",
      "macOS"
    ],
    [
      "runtime",
      "Electron 28.3.3"
    ],
    [
      "runtime.name",
      "Electron"
    ],
    [
      "release",
      "xxx"
    ],
    [
      "user",
      "xxx"
    ],
    [
      "url",
      "xxx"
    ]
  ],
```

This will make environment field to be "--" on Sentry ui.
Image

This only happens in **production mode**. In development mode, there is an "environment" tag,

```json
 "tags": [
    [
      "browser.name",
      "Chrome"
    ],
    [
      "chrome",
      "Chrome 120.0.6099.291"
    ],
    [
      "chrome.name",
      "Chrome"
    ],
    [
      "device.family",
      "Desktop"
    ],
    [
      "environment",
      "development"
    ],
    [
      "event.environment",
      "javascript"
    ],
    [
      "event.origin",
      "electron"
    ],
    [
      "event.process",
      "renderer"
    ],
    [
      "handled",
      "yes"
    ],
    [
      "level",
      "error"
    ],
    [
      "mechanism",
      "generic"
    ],
    [
      "node",
      "Node 18.18.2"
    ],
    [
      "node.name",
      "Node"
    ],
    [
      "os",
      "macOS 13.3.1"
    ],
    [
      "os.name",
      "macOS"
    ],
    [
      "runtime",
      "Electron 28.3.3"
    ],
    [
      "runtime.name",
      "Electron"
    ],
    [
      "release",
      "xxx"
    ],
    [
      "user",
      "xxx"
    ],
    [
      "url",
      "xxx"
    ]
  ],
```

### Expected Result

Can see which environment the error occurs

### Actual Result

Missing the environment field

--

But If I only import sentry react, the environment tag appears.
It seems that using only sentry react works for catching correct errors and environment.
```js
import * as Sentry from '@sentry/react'

Sentry.init({
  dsn: import.meta.env.VITE_SENTRY_DSN,
  environment: process.env.NODE_ENV
})
```

error json
```json
"tags": [
    [
      "browser",
      "Electron 28.3.3"
    ],
    [
      "browser.name",
      "Electron"
    ],
    [
      "device",
      "Mac"
    ],
    [
      "device.family",
      "Mac"
    ],
    [
      "environment",
      "production"
    ],
    [
      "handled",
      "yes"
    ],
    [
      "level",
      "error"
    ],
    [
      "mechanism",
      "generic"
    ],
    [
      "os",
      "Mac OS X \u003E=10.15.7"
    ],
    [
      "os.name",
      "Mac OS X"
    ],
    [
      "release",
      "xxx"
    ],
    [
      "user",
      "xxx"
    ],
    [
      "url",
      "xxx"
    ]
  ],
```

The fields received are different.

Please advise, thanks!

### PR DESCRIPTION
**Pull request by timfish**
- Closes #1030

In the Electron SDK, most of Sentry configuration occurs on the Electron main process because that is where all envelopes are sent from.

We don't support or test setting `dsn`, `environment` and `release` from renderer processes so this should be more clear from the types.

### CODE REVIEW

File: src/renderer/sdk.ts [hunk 1]
```diff
@@ -32,6 +32,13 @@ interface ElectronRendererOptions extends BrowserOptions {
    * Defaults to 'false'.
    */
   anrDetection?: Partial<RendererProcessAnrOptions> | boolean;
+
+  /** @deprecated dsn should only be passed in the main process */
```
Comment (AbhiPrasad) [inline src/renderer/sdk.ts:36]: ditto for the rest.

```suggestion
  /** @deprecated dsn should only be passed in the main process `Sentry.init` call */
```

**Review by AbhiPrasad — APPROVED** [review]
