### PR TITLE
fix: Check preload path is absolute

### LINKED ISSUE #491: preload script must have absolute path
## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.7`
- [x] Electron version - `electron@v18.2.0`
- [x] Platform - `macOS`

## Description

There are lots of error messages coming from the main process:

```
[22375:0526/171429.459534:ERROR:session_preferences.cc(38)] preload script must have absolute path: ../../common/temp/node_modules/.pnpm/@sentry+electron@3.0.7/node_modules/@sentry/electron/esm/preload/index.js
```

Screen Shot 2022-05-26 at 5 16 58 PM

### PR DESCRIPTION
**Pull request by timfish**
Closes #491

It looks like webpack can convert `require.resolve` to relative paths that Electron then complains about. 

This change ensures that we only attempt to use preload paths that came from `require.resolve`, ie. only absolute paths will be attempted.

### CODE REVIEW

File: src/main/integrations/preload-injection.ts [hunk 1]
```diff
@@ -49,7 +50,7 @@ export class PreloadInjection implements Integration {
       //
     }
 
-    if (path && typeof path === 'string' && existsSync(path)) {
+    if (path && typeof path === 'string' && isAbsolute(path) && existsSync(path)) {
```
Comment (AbhiPrasad) [inline src/main/integrations/preload-injection.ts:53]: Can we log out an error if the path is not absolute? Or atleast attempt to log out the path in the debug message below?

**Review by AbhiPrasad — APPROVED** [review]

File: src/main/integrations/preload-injection.ts (hunk 1 above)
Comment (timfish) [reply src/main/integrations/preload-injection.ts:53]: I would be wary of logging any warnings here since all this change actually does it stop Electron from logging warnings about preload non-absolute paths. 

If injecting preload fails, we fallback to custom protocol + `fetch` so the SDK should continue to function as normal.

Comment (AbhiPrasad) [reply src/main/integrations/preload-injection.ts:53]: Ah ok that makes sense, thanks for the details!
